apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: qa
      - env: prod

  template:
    metadata:
      name: todo-{{env}}
      labels:
        app_env: "{{env}}"

    spec:
      project: todo
      destination:
        server: https://host.docker.internal:26443
        namespace: todo-{{env}}

      source:
        repoURL: https://github.com/mturnaviotov/go-k8s-test-app.git
        targetRevision: HEAD
        path: charts/
        helm:
          valueFiles:
          - "environments/{{env}}/values.yaml"
          parameters:
          - name: git.commit
            value: "{{revision}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
