apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Todo
  sourceRepos:
  - "*"
  destinations:
  - namespace: "*"
    server: "*"
namespaceResourceWhitelist:
- group: '*'
  kind: '*'
clusterResourceWhitelist:
- group: '*'
  kind: '*'
