apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Todo
  sourceRepos:
  - "*"
  destinations:
  - namespace: "todo"
    server: "orbstack"
  - namespace: "todo-dev"
    server: "orbstack"
  - namespace: "todo-prod"
    server: "orbstack"
namespaceResourceWhitelist:
- group: '*'
  kind: '*'
clusterResourceWhitelist:
- group: '*'
  kind: '*'
